[workspace]
members = [
    "stat-info",
    "stat-test"
]

resolver = "2"

[workspace.package]
authors = ["Alexander Manov", "Nikola Peshev"]
edition = "2021"
include = ["src/**/*.rs"]
license = "MIT"
repository = "https://github.com/AEManov20/stat-info.git"